apiVersion: v1
kind: Service
metadata:
  name: deepguard-service
  labels:
    app: deepguard
spec:
  type: LoadBalancer
  selector:
    app: deepguard
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
